image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 13

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules
  - app/node_modules
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  # TODO : Need to start again by finding a better credential mgmt
  # Stopping packaging for git credentials
  # - yarn package-ci
  - yarn lint
  - yarn ts
  # TODO : Need to start again by finding a better credential mgmt
  # Stopping test for git credentials(as it includes build and now build is failing)
  - yarn test
